name: blue
type: kubernetes
endpoint_name: tf-mnist
app_insights_enabled: true
model:
  path: ./model/
code_configuration:
  code: ./script/
  scoring_script: score.py
instance_type: myinstancetypename
environment:
  image: mcr.microsoft.com/azureml/openmpi3.1.2-cuda10.2-cudnn8-ubuntu18.04
  conda_file: ./model/conda.yml
request_settings:
  request_timeout_ms: 3000
  max_concurrent_requests_per_instance: 1
  max_queue_wait_ms: 3000
resources:
  requests:
    cpu: "0.1"
    memory: "500Mi"
  limits:
    cpu: "0.2"
    memory: "1Gi"
    nvidia.com/gpu: "1"
liveness_probe:
  initial_delay: 10
  period: 10
  timeout: 10
  success_threshold: 1
  failure_threshold: 1
readiness_probe:
  initial_delay: 10
  period: 10
  timeout: 10
  success_threshold: 1
  failure_threshold: 1
scale_settings:
  type: default