name: blue
type: kubernetes
endpoint_name: tf-mnist
app_insights_enabled: true
model:
  name: tf-mnist
  local_path: ./model/
code_configuration:
  code:
    name: "score"
    local_path: ./script/
  scoring_script: score.py
instance_type: myinstancetypename
environment: 
  name: tf-mnist-model
  image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:20210727.v1
  conda_file: ./model/conda.yml
request_settings:
  request_timeout_ms: 3000
  max_concurrent_requests_per_instance: 1
  max_queue_wait_ms: 3000
resources:
  requests:
    cpu: "0.1"
    memory: "0.1Gi"
  limits:
    cpu: "0.2"
    memory: "0.2Gi"
    nvidia.com/gpu: "1"
liveness_probe:
  initial_delay: 10
  period: 10
  timeout: 10
  success_threshold: 1
  failure_threshold: 1
readiness_probe:
  initial_delay: 10
  period: 10
  timeout: 10
  success_threshold: 1
  failure_threshold: 1
