# -*- coding: utf-8 -*-
#
# Generic entry script for submitting a run in AML.
#
# Generated by pacodegen-0.4.2 on 2019-10-10 05:38:04.306427+00:00
#

import os
import sys
import argparse
import urllib.parse

#

parser = argparse.ArgumentParser(description="AML Generic Entry Script")
parser.add_argument("--command", required=True, help="the command to run in url encoding")

_, unknown = parser.parse_known_args()
for x in unknown:
    if x.startswith("--env_"):
        parser.add_argument(x)
args = parser.parse_args()

for key, value in vars(args).items():
    if key.startswith("env_"):
        os.environ[key[len("env_"):]] = urllib.parse.unquote(value)

return_code = os.system(urllib.parse.unquote(args.command))
sys.exit(return_code >> 8)

#
# (END)
