amlModuleIdentifier:
  namespace: microsoft.com/aml/samples
  moduleName: "Train"
  moduleVersion: 0.0.5
inputs:
- name: training_data
  type:
  - AnyFile
  - AnyDirectory
  label: Training data organized in the torchvision format/structure
- name: max_epochs
  type: Integer
  label: Maximum number of epochs for the training
- name: learning_rate
  type: Float
  default: 0.01
  label: Learning rate, default is 0.01
outputs:
- name: model_output
  type: AnyFile
  label: The output model (zipped)
implementation:
  container:
    amlEnvironment:
      python:
        condaDependencies:
          name: project_environment
          channels:
            - defaults
          dependencies:
            - python=3.6.8
            - pip:
              - azureml-defaults
    command: [python, train.py]
    args: [
      --training_data, {inputPath: training_data},
      --max_epochs, {inputValue: max_epochs},
      --learning_rate, {inputValue: learning_rate},
      --model_output, {outputPath: model_output},
    ]