apiVersion: v1
data:
  mounts.yaml: |
    mountPoints:
    - mountPath: /nfs_share
      mountType: nfs
      name: amlarc-nfs-share-0
      path: /disks/4TB/code/nfs_share
      server: <nfs-server-ip>
kind: ConfigMap
metadata:
  name: mount-config
  namespace: azureml
