name: Portal Provision PR Gate
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, mingj/gate ]
    # TODO: move these files into a folder
    paths:
      - files/deploy.py
      - files/entry.sh
  pull_request:
    branches: [ master, mingj/gate ]
    # TODO: move these files into a folder
    paths:
      - files/deploy.py
      - files/entry.sh
jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Extract branch name
          shell: bash
          run: |
            if [ $EVENT_NAME = "push" ]
            then
              echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
            else
              echo "##[set-output name=branch;]$(echo $BASE_BRANCH)"
            fi
          env:
            BASE_BRANCH: ${{ github.base_ref }}
            EVENT_NAME: ${{ github.event_name }}
          id: extract_branch

        - uses: actions/setup-python@v3          

        - name: Install dependencies
          shell: bash
          run: |
            pip install msrest
            pip install azure-devops
          id: install_dependencies

        - name: Run pipeline
          shell: bash
          env:
            PAT_TOKEN: ${{ secrets.AMLARC_PORTAL_PROVISION_PIPELINE_PAT }}
            BRANCH: ${{ steps.extract_branch.outputs.branch }}
          run: python .github/run_pipeline.py --definition-id 21230 --variables GITHUB_BRANCH=$BRANCH
          id: run_pipeline
